name: Compile LaTeX Document and Create Release

on:
  push:
    tags:
      - "*"

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compile Resume
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_use_xelatex: true
          root_file: dcresume.tex

      - name: Release Resume
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Corley Resume - ${{ github.ref_name }}
          files: dcresume.pdf
